### Get user documentation
GET {{host}}/user/document HTTP/1.1

### Create a new user
POST {{host}}/user HTTP/1.1
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "QQww!!22",
    "username": "tester"
}

### Get a user
GET {{host}}/user/18dcd37c-5342-4dee-808a-c568fbc9d17a HTTP/1.1
Authorization: Bearer {{auth_token}}

### Get all users
GET {{host}}/user HTTP/1.1
Authorization: Bearer {{auth_token}}

### Patch a user
PATCH {{host}}/user/18dcd37c-5342-4dee-808a-c568fbc9d17a HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "username": "tester22"
}

### Delete a user
DELETE {{host}}/user/54e8a827-8f1b-42e6-9c87-67a3304d160a HTTP/1.1