### Get user documentation
GET {{host}}/users/document HTTP/1.1

### Create a new user
POST {{host}}/users HTTP/1.1
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "QQww!!22",
    "username": "tester"
}

### Get a user
GET {{host}}/users/966f86e0-eee8-4eeb-af1d-6e6ec49e6c8a HTTP/1.1
Authorization: Bearer {{auth_token}}

### Get all users
GET {{host}}/users HTTP/1.1
Authorization: Bearer {{auth_token}}

### Patch a user
PATCH {{host}}/users/18dcd37c-5342-4dee-808a-c568fbc9d17a HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "username": "tester22"
}

### Patch user's roles
PATCH {{host}}/users/roles/966f86e0-eee8-4eeb-af1d-6e6ec49e6c8a HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "roles": ["user"]
}

### Delete a user
DELETE {{host}}/users/a0aa6ea6-c606-415e-99ea-5a5fd28cfa9c HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{auth_token}}