### GET Goals list
GET {{host}}/goals/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{auth_token}}

### POST Create a goal
POST {{host}}/goals/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "name": "user eligible goal",
  "metadata": {
    "description": "let's test it out!"
  },
  "private": true
}

### Find one goal
GET {{host}}/goals/42fe4774-490e-498d-accd-d948be25b860 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{auth_token}}

### Patch a goal
PATCH {{host}}/goals/cfeb9fc6-cb7f-4a0c-96e2-ca45e4f720bb
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "contributors": [
    "966f86e0-eee8-4eeb-af1d-6e6ec49e6c8a",
    "5e0bbba8-fee5-4151-8266-58dfa31047d8"
  ],
  "subgoals": [
    "5ffaf898-f8e1-4432-99fb-3319d2584a99",
    "6d5045d9-ab9c-4bb1-afa7-771f4c86f552"
  ]
}

### Delete a goal
DELETE {{host}}/goals/5c424ec7-7c94-4a34-b63c-2aa1773f98db
Content-Type: application/json
Authorization: Bearer {{auth_token}}