### GET Goals list
GET {{host}}/goals/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{auth_token}}

### POST Create a goal
POST {{host}}/goals/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "name": "user contributing goal",
  "metadata": {
    "description": "let's test it out!"
  },
  "private": true
}

### Find one goal
GET {{host}}/goals/40174db4-2ecb-4d99-8c2e-a65a5c4d6bcc HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{auth_token}}

### Patch a goal
PATCH {{host}}/goals/40174db4-2ecb-4d99-8c2e-a65a5c4d6bcc
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "contributors": [
    "fa59dd7d-07bb-40f0-a1b9-275c026048b8"
  ],
  "subgoals": [
    "20f9a1ef-30d7-4911-a5fe-0035fe78d770"
  ]
}

### Delete a goal
DELETE {{host}}/goals/5c424ec7-7c94-4a34-b63c-2aa1773f98db
Content-Type: application/json
Authorization: Bearer {{auth_token}}