### GET Goals list
GET {{host}}/goals/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{auth_token}}

### POST Create a goal
POST {{host}}/goals/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "name": "my first goal",
  "metadata": {
    "description": "let's test it out!"
  },
  "private": true
}

### Find one goal
GET {{host}}/goals/cfeb9fc6-cb7f-4a0c-96e2-ca45e4f720bb HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{auth_token}}

### Patch a goal
PATCH {{host}}/goals/cfeb9fc6-cb7f-4a0c-96e2-ca45e4f720bb
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "name": "my second goal",
  "metadata": {
    "description": "let's rock it out!"
  },
  "private": false
}

### Delete a goal
DELETE {{host}}/goals/5c424ec7-7c94-4a34-b63c-2aa1773f98db
Content-Type: application/json
Authorization: Bearer {{auth_token}}