### Login as a user
# @name login
POST http://localhost:3000/auth/login HTTP/1.1
Content-Type: application/json

{
    "email": "te1stt@test.com",
    "password": "QQww!!22"
}

### GET current user
@accessToken = {{login.response.body.access_token}}

GET http://localhost:3000/auth/profile HTTP/1.1
Authorization: Bearer {{accessToken}}