name: Build and Push

on:
  pull_request:
    branches: [ main ]
    types: [ closed ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
          ref: ${{ github.event.pull_request.merge_commit_sha }}
      - name: Automatic Tagging of Releases
        id: increment-git-tag
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INITIAL_VERSION: 0.8.0
      - name: Publish to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: miksiv/go-getter
          tags: latest, ${{ steps.increment-git-tag.outputs.new_tag }}
